### ISSUE TITLE
How do I run the code in .py instead of jupyter notebook?

### ISSUE THREAD

**Issue by DarcyFan** [PeizhiYan/flame-head-tracker#1]
Hi, Thanks for your open source, and I successfully run the exsample.ipynb on my own video.
But, I found that when I took the code from .ipynb format becomes .py format, the code will suddenly terminate.
And is there any solution you know？

This is the code from .py file:
``` python
## Enviroment Setup
import os, sys
WORKING_DIR = 'D:/MyCode/flame-head-tracker-1.1' # download the flame-head-tracker from github
os.chdir(WORKING_DIR) # change the working directory to the project's absolute path
print("Current Working Directory: ", os.getcwd())

## Computing Device
device = 'cuda:0'
import torch
torch.cuda.set_device(device) # this will solve the problem that OpenGL not on the same device with torch tensors

sys.path.append(WORKING_DIR)
sys.path.append('./utils/flame_lib/')
sys.path.append('./utils/flame_fitting/')
sys.path.append('./utils/face_parsing/')
sys.path.append('./utils/decalib/')
sys.path.append('./utils/mesh_renderer')
sys.path.append('./utils/scene')

from time import time

from tracker_video import track_video_legacy   # will fit and save one frame at a time
from tracker_video import track_video          # faster than the legacy code, save at the end

personal_video_path = r"C:\Users\hp\Desktop\input.mp4"  # video file path
save_path = f'C:/Users/hp/Desktop/output2'
try: 
    os.makedirs(save_path)
except Exception as e:
    print(e)


tracker_cfg = {
    'mediapipe_face_landmarker_v2_path': './models/face_landmarker_v2_with_blendshapes.task',
    'flame_model_path': './models/FLAME2020/generic_model.pkl',
    'flame_lmk_embedding_path': './models/landmark_embedding.npy',
    'tex_space_path': './models/FLAME_texture.npz',
    'face_parsing_model_path': './utils/face_parsing/79999_iter.pth',
    'uv_coord_mapping_file_path': './models/uv2vert_256.npy',
    'template_mesh_file_path': './models/head_template.obj',
    'result_img_size': 512,
    'device': device,
    ## following are used for video tracking
    'original_fps': 30,        # input video fps
    'subsample_fps': 15,       # subsample fps
    'video_path': personal_video_path, # personal video file path
    'save_path': save_path,   # tracking result save path
    'use_kalman_filter': False, # whether to use Kalman filter
    'kalman_filter_measurement_noise_factor': 1e-5, # measurement noise level in Kalman filter 
    'kalman_filter_process_noise_factor': 1e-5,     # process noise level in Kalman filter 
}
## Note that, the first frame will take longer time to process
dt = time()
track_video_legacy(tracker_cfg)
print(f"time used: {(time() - dt) / 60} minutes")
```

And this is the terminal output:
```
Current Working Directory:  D:\MyCode\flame-head-tracker-1.1
Conversion completed. 655
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1732516727.886329   70996 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1732516727.935456   73304 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1732516727.946896   12168 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
creating the FLAME Decoder
Error in sys.excepthook:

Original exception was:
```

**Comment by PeizhiYan** [comment]
Hi there! Thank you for bringing up this potential issue. I noticed that you’re using the v1.1 code. Would you mind trying our latest version, v2.0? I’ve tested it on Ubuntu, and it worked without issues.

Since the terminal output didn’t include the details of the exception, I suggest adding the following lines to help with debugging:

```
import sys
sys.excepthook = sys.__excepthook__
import traceback
```
and 
```
try:
    track_video_legacy(tracker_cfg)
    raise RuntimeError("Testing exception handling")
except Exception as e:
    print("Caught an exception manually:")
    traceback.print_exc()
```

This should provide more detailed information about the error. Let me know if this helps!

**Comment by DarcyFan** [comment]
> Hi there! Thank you for bringing up this potential issue. I noticed that you’re using the v1.1 code. Would you mind trying our latest version, v2.0? I’ve tested it on Ubuntu, and it worked without issues.
> 
> Since the terminal output didn’t include the details of the exception, I suggest adding the following lines to help with debugging:
> 
> ```
> import sys
> sys.excepthook = sys.__excepthook__
> import traceback
> ```
> 
> and
> 
> ```
> try:
>     track_video_legacy(tracker_cfg)
>     raise RuntimeError("Testing exception handling")
> except Exception as e:
>     print("Caught an exception manually:")
>     traceback.print_exc()
> ```
> 
> This should provide more detailed information about the error. Let me know if this helps!

Thanks for your reply!
I have changed the latest version v2.0 and the successfully run the code with .py format on Windows!
I don't know what the v1.1 issue was, but somehow it solved my problem.
Thanks again for your advice!

**Comment by PeizhiYan** [comment]
> > Hi there! Thank you for bringing up this potential issue. I noticed that you’re using the v1.1 code. Would you mind trying our latest version, v2.0? I’ve tested it on Ubuntu, and it worked without issues.
> > Since the terminal output didn’t include the details of the exception, I suggest adding the following lines to help with debugging:
> > ```
> > import sys
> > sys.excepthook = sys.__excepthook__
> > import traceback
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > try:
> >     track_video_legacy(tracker_cfg)
> >     raise RuntimeError("Testing exception handling")
> > except Exception as e:
> >     print("Caught an exception manually:")
> >     traceback.print_exc()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should provide more detailed information about the error. Let me know if this helps!
> 
> Thanks for your reply! I have changed the latest version v2.0 and the successfully run the code with .py format on Windows! I don't know what the v1.1 issue was, but somehow it solved my problem. Thanks again for your advice!

Good to know! You're welcome. I'll go ahead and mark this issue as resolved.
